name: Install + Build + Deploy
permissions:
  contents: read
on:
  push:
    branches: [main]

jobs:
  build-deploy:
    uses: Plyaz-Official/devtools/.github/workflows/deploy.yml@main
    secrets: inherit